# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db-pass-1
    volumes:
#      - mysql_data:/var/lib/mysql
      - ./scripts/CreateDb.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/CreatePersonsTable.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/CreatePersonsTableUsers.sql:/docker-entrypoint-initdb.d/3.sql
    ports:
      - '3306:3306'

#volumes:
#  mysql_data:
